version: "3"
services:
  web:
    build: . # compile docker image from current directory
    ports:
      - "5000:5000"
    environment:
      ANAGRAM_DB_HOST: "database"
      ANAGRAM_DB_PORT: "5432"
      ANAGRAM_DB_NAME: "anagram"
      ANAGRAM_DB_USER: "anagram"
      ANAGRAM_DB_PASS: "ch@ng3it"
      ANAGRAM_LOG_LEVEL: "INFO"
      ANAGRAM_SECRET_KEY: "YOUR_SECRET_KEY_HERE"
    links:
      - "database:database"
    depends_on:
      - database
  database:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "anagram"
      POSTGRES_PASSWORD: "ch@ng3it"
      POSTGRES_DB: "anagram"
